dataset: 'mogaze'
t_his: 15
t_pred: 60
batch_size: 32
num_epoch: 501
num_data_sample: 50000
num_val_data_sample: 5000
lr: 3.e-4
n_pre: 10
multimodal_path: ./data/mogaze_1test_multi_modal/t_his15_1_thre0.400_t_pred60_thre0.100_index_subp1_1.npz
data_candi_path: ./data/mogaze_1test_multi_modal/mogazeglobal_withcontext_t_his15_t_pred60_skiprate15.npz
padding: 'LastFrame'
Complete: True
noise_steps: 1500
ddim_timesteps: 100
scheduler: 'Cosine' # 'Cosine' 'Linear' 'Sqrt' 'Sigmoid'
num_layers: 4
num_heads: 8
latent_dims: 512
dropout: 0.2
mod_train: 1.0
mod_test: 1.0
dct_norm_enable: False
latent_features: 128
residual_gcns_num: 4
